version: '3.9'

services:
  # BD
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - cifra-net

  # Back
  backend:
    build:
      context: ./back-cifra-pay
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - cifra-net

  # Frontend 
  frontend:
    build:
      context: ./front-cifra-pay
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - cifra-net

volumes:
  db_data:

networks:
  cifra-net:
    driver: bridge
